# This is a workflow to build the Graph Explorer application in .NET Core

name: Build.GraphExplorer.netcore

# Controls when the action will run. Triggers the workflow on push or pull request
# events for any branch.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout the code...
          uses: actions/checkout@v2

        - name: Setup .NET core
          uses: actions/setup-dotnet@v1
          with:
             dotnet-version: '3.1.100' # SDK Version to use.

        - name: Build and publish
          run: dotnet publish -r win-x64  --self-contained true -c Release -p:PublishSingleFile=true  "tools\Graph Explorer\GraphExplorer.netcore.csproj"

        - name: Upload compiled app so it can be downloaded.
          uses: actions/upload-artifact@v1
          with:
             name: SocrateX.GraphExplorer.netcore
             path: "tools\\Explorer\\bin\\Release\\netcoreapp3.1\\win-x64\\publish"
      
