# This is a workflow to build the AST Explorer application

name: Build.Explorer

# Controls when the action will run. Triggers the workflow on push or pull request
# events for any branch.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    - name: Restore Packages for BaseXInterface project
      run: nuget restore tools\BaseXInterface\BaseXInterface.csproj
     
    - name: Restore Packages for Explorer project
      run: nuget restore "tools\Explorer\Socratex Explorer.csproj"
     
    - name: Setup msbuild.exe
      uses: microsoft/Setup-MSBuild@v1.0.2
     
    - name: Build BaseXInterface with MSBuild
      run: msbuild tools\BaseXInterface\BaseXInterface.csproj
    - name: Build Explorer with MSBuild
      run: msbuild "tools\Explorer\Socratex Explorer.csproj"
      
